//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootcampversi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_TransactionDetail
    {
        public int Id { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual TB_M_Items TB_M_Items { get; set; }
        public virtual TB_M_Sell TB_M_Sell { get; set; }
    }
}
